/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.snake;

import java.awt.Graphics;
import javax.swing.Timer;

/**
 *
 * @author alu10772822
 */
public class Board extends javax.swing.JPanel {
    
    public static final int NUM_ROWS = 16;
    public static final int NUM_COLS = 16;
    private Timer timer;
    private Snake snake;
    /**
     * Creates new form Board
     */
    public Board() {
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myInit(){
        snake = new Snake(Direction.RIGHT);
        
    }
    
    protected void paintComponent(Graphics g){
        snake.paintSnake(g, squareWidth(), squareHeight());
    }
    
    public int squareWidth() {
        return getWidth() / Board.NUM_COLS;
    }
    
    public int squareHeight() {
        return getHeight() / Board.NUM_ROWS;
    }
    
//    private boolean canMove(int row,int col){
//        
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
